config/routes.rb
Instagram::Application.routes.draw do
  devise_for :users
  resources :tags, only: [:show]

  root 'posts#index'
  resources :posts do
    resources :comments
    resources :charges
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :description, presence: true

	has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>", :large => "550x550"},
	storage: :s3,
  bucket: 'bonobospics',
  s3_credentials: {
    access_key_id: Rails.application.secrets.s3_access_key,
    secret_access_key: Rails.application.secrets.s3_secret_key
   }
	validates_attachment_content_type :picture, content_type: ["image/jpg", "image/jpeg", "image/png"]

	has_and_belongs_to_many :tags 
	has_many :comments
	

	def tag_names
		tags.map(&:name).join
	end

	def tag_names=(tag_names)
		self.tags = tag_names.split(' ').uniq.map do |tag_name|
			tag_name.prepend("#") unless tag_name[0] == "#"
			Tag.find_or_create_by(name: tag_name.downcase)
		end
	end

end

app/models/tag.rb
class Tag < ActiveRecord::Base

	has_and_belongs_to_many :posts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :username
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => 'example@stripe.com',
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => 'Rails Stripe customer',
	    :currency    => 'gbp'
	  )

	  flash[:notice] = "Thanks for the dollar dollar!"
	  redirect_to '/posts'

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find params[:post_id]
    @comment = Comment.new
  end

  def create
    @post = Post.find params[:post_id]
    @post.comments.new params[:comment].permit(:content)

    if @post.save
      flash[:notice] = 'Thanks for your comment'
      redirect_to '/posts'
    else
      render 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def index
		@posts = Post.all 
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to '/posts'
		else
			flash[:errors] = "Please submit a valid post"
			render 'new'
		end
	end

	def destroy
		@post = Post.find params[:id]
		@post.destroy
		flash[:notice] = "Post Deleted!"
		redirect_to '/posts'
	end

	def edit
		@post = Post.find params[:id]
	end

	def update
		@post = Post.find params[:id]
		@post.update post_params
		flash[:notice] = "Post updated successfully"
		redirect_to '/posts'
	end

	def post_params
		params[:post].permit(:description, :picture, :tag_names)
	end

	def show
		@post = Post.find params[:id]
	end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
  	@tag = Tag.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag post_charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"></script>
<% end %>

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content, 'Add a Comment' %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Instagram', posts_path, class: 'navbar-brand' %>  
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li>
            <p class="navbar-brand"><h5>Signed in as <%= current_user.email %><h5><p>
          </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-camera"> Photos <b class="caret"></b></a></span>
          <ul class="dropdown-menu">
            <li><a href="#">Add photo</a></li>
            <li><a href="#">Delete photo</a></li>
            <li><a href="#">Edit photo</a></li>
            <li class="divider"></li>
            <li><a href="#">Profile Page</a></li>
            <li class="divider"></li>
            <li><a href="#">Contact Us</a></li>
          </ul>
        </li>
        <li>
          <%= link_to ' Sign out', destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-remove" %>
        </li>
        <% else %>
          <li>
            <%= link_to ' Sign in', new_user_session_path, class: "glyphicon glyphicon-import" %>
          </li>  
          <li>
            <%= link_to ' Sign up', new_user_registration_path, class: "glyphicon glyphicon-plus" %>
          </li>  
        <% end %>      
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "posts", media: "all", "data-turbolinks-track" => true %>  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>

<body>

<%= render 'layouts/header' %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

<%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"%>
<%= javascript_include_tag "bootstrap.min.js"%>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :class => 'new_form', :html => { :multipart => true } do |f| %>
  <div id="new_post_description_row">
    <%= f.label :description, :class => 'new_post_description' %>
    <%= f.text_area :description, :class => "new_post_description_label" %>
  </div>
  <div id="new_post_tags_row">
    <%= f.label :tag_names, :class => 'new_post_tags' %>
    <%= f.text_area :tag_names, :class => "new_post_tags_label" %>
  <p> </p>
  <div>
    <%= f.label :picture, :class => "new_post_picture_label" %>
    <%= f.file_field :picture, :class => "new_post_picture" %>
  </div>
  <%= f.submit :class => "btn btn-primary", id: "udpdate-tv"  %>
<% end %>

app/views/posts/_post.html.erb
<div class="photo">
	<div class="thumbnail">
		<%= image_tag post.picture.url(:medium), class: 'uploaded-pic' %>
		<div class="caption">
 			<h3><%= post.description %></h3>
 			<% post.tags.each do |tag| %>
 				<%= link_to tag.name, tag %>
 			<% end %></br>
 			<h5><%= pluralize post.comments.count, 'comments' %>  </h5>
  		<%= link_to ' View', post_path(post), class: "glyphicon glyphicon-picture"  %>
  		<%= link_to 'Add a comment', new_post_comment_path(post), class: "glyphicon glyphicon-pencil" %></br></br>
  		<%= link_to ' Edit', edit_post_path(post), class: 'glyphicon glyphicon-pencil' %>
  		<%= link_to ' Delete', post_path(post), method: :delete, class: 'glyphicon glyphicon-remove' %>
  		<%= link_to ' Print pic', new_post_charge_path(post), class: 'glyphicon glyphicon-print' %>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>
<%= image_tag @post.picture.url(:medium), class: 'uploaded-pic' %>

app/views/posts/index.html.erb
<div class="container">
	<div class="jumbotron">
	  <div class="container">
	    <p> Black and white photos of random people's breakfast. I'm talking literally cereal. And it's being shared here.<p>Oddly saturated photos of that same road you walk past every morning. People thinking they're deep for taking a photo of a slug.</p></p>
	    <h4> Welcome to Instagram! </h4>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      	<ul class="nav navbar-nav">
      		<li><a href="posts/new"><span class="glyphicon glyphicon-plus"></span> Add a picture</a></li>
      		<li><a href="#"><span class="glyphicon glyphicon-picture"></span> View a random pic</a></li>
      		<li><a href="#"><span class="glyphicon glyphicon-star"></span> The Special Gallery</a></li>
      	</ul>
      </div>
	  </div>
	</div>
</div>
<div class="post_container">
	<% if @posts.any? %>
		<div class="posts">
				<%= render @posts %>
		</div>
	<% else %>
		No posts yet
	<% end %>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="photo">
	<div class="thumbnail">
		<%= image_tag @post.picture.url(:medium), class: 'uploaded-pic' %>
		<div class="caption">
 			<h3><%= @post.description %></h3>
 			<% @post.tags.each do |tag| %>
 				<%= link_to tag.name, tag %>
 			<% end %>
  		<h5><%= pluralize @post.comments.count, 'comments' %>  </h5>
  		<%= link_to 'View', post_path(@post), class: "glyphicon glyphicon-picture"  %>
  		<%= link_to 'Add a comment', new_post_comment_path(@post), class: "glyphicon-pencil" %></br>
  		<%= link_to 'Edit', edit_post_path(@post), class: 'glyphicon glyphicon-pencil' %>
  		<%= link_to ' Delete', post_path(@post), method: :delete, class: 'glyphicon glyphicon-remove' %>
		</div>
	</div>
</div>

<div id="comment_container">
	<% @post.comments.each do |comment| %>
		<div id="comments_container">
			<%= comment.content %>
		</div>
	<% end %></br></br>
</div>

app/views/tags/show.html.erb
<div class="container">
	<div class="jumbotron">
	    <p> Photos tagged with <%= @tag.name %></p>
	</div>
</div>
<%= render @tag.posts %>